### ISSUE TITLE
replication from other slave doesnt work

### ISSUE THREAD

**Issue by walito** [noplay/python-mysql-replication#172] opened 2016-09-09 14:53 UTC
Hello, Im trying to run replication from other slave (log_slave_updates) but I cant get EVENTs, these are empty.

There is a BUG? or the replication doesnt work from other slave?

Thanks in advance

=== UpdateRowsEvent ===
Date: 2016-09-09T13:47:46
Log position: 1690915
Event size: 935
Read bytes: 13
Table: XXXX.ZZZZZ
Affected columns: 10
Changed rows: 0
Affected columns: 10
Values:
()

=== WriteRowsEvent ===
Date: 2016-09-09T13:47:46
Log position: 1689821
Event size: 160
Read bytes: 11
Table: XXXX.ZZZZZ
Affected columns: 10
Changed rows: 0
Values:
()

**Comment by facundo-guerrero-olx** [comment] 2016-09-13 14:20
It's the binlog in Row? I always using this from a Slave.

**Comment by walito** [comment] 2016-09-13 14:46
yes, Im using format row

MASTER ---------> SLAVE1 (log_slave_updates ON) ----------> SLAVE2 (mysql work fine)
                                                                                \---------> python-mysql-replication (doesnt work)


Thanks in advance

**Comment by bjoernhaeuser** [comment] 2016-12-17 20:52
@walito is your user able to read the information schema tables? See here https://github.com/noplay/python-mysql-replication/pull/184

In general we are used the same topology you have without any issue. Closing this therefore. Please reopen if the issue is not resolved.

**Closed by bjoernhaeuser** 2016-12-17 20:52 UTC
