### ISSUE TITLE
`IndexError` in TableMapEvent

### ISSUE THREAD

**Issue by lxyu** [noplay/python-mysql-replication#36] opened 2013-06-06 04:34 UTC
```python
Traceback (most recent call last):
  File "/srv/virtualenvs/zeus/local/lib/python2.7/site-packages/pymysqlreplication/binlogstream.py", line 118, in fetchone
    self._ctl_connection)
  File "/srv/virtualenvs/zeus/local/lib/python2.7/site-packages/pymysqlreplication/packet.py", line 88, in __init__
    ctl_connection)
  File "/srv/virtualenvs/zeus/local/lib/python2.7/site-packages/pymysqlreplication/row_event.py", line 488, in __init__
    column_schema = self.column_schemas[i]
IndexError: tuple index out of range
```

More info:
```python
>>> print column_types
['\x03', '\x03', '\x03', '\x0f', '\x0f', '\x03', '\x0c', '\x0c']
>>> print self.columns
[]
>>> print table_map
{}
>>> print self.column_schemas
()
```

And the `self.packet.read_length_coded_binary()` at L485 returns 4.

Put this line in the first line of TableMapEvent __init__ shows this:
```python
>>> print repr(self.packet.read(58))
'N\x01\x00\x00\x00\x00\x01\x00\x06sentry\x00\x19sentry_messagefiltervalue\x00\x08\x03\x03\x03\x0f\x0f\x03\x0c\x0c\x04`\x00X\x02\xe0'
```

**Comment by psypuff** [comment] 2015-05-05 10:14
Hi, looks like this issue has been open for a while... :grin: 

We've recently got this similar exception on our production env:
```
Traceback (most recent call last):
  File "my_script.py", line 107, in <module>
    for binlogevent in stream:
  File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/binlogstream.py", line 244, in fetchone
    only_schemas = self.__only_schemas)
  File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/packet.py", line 94, in __init__
    only_schemas = only_schemas)
  File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/row_event.py", line 512, in __init__
    column_schema = self.column_schemas[i]
IndexError: tuple index out of range
```

I guess the issue is still open `cause there's no fix yet...
Is there any fix planned?

**Comment by noplay** [comment] 2015-05-05 12:58
@bjoernhaeuser @lxyu what did you think? I can add the fix you proposed if you didn't have another idea since.

**Comment by bjoernhaeuser** [comment] 2015-05-09 18:34
@noplay No idea from me :-(

**Comment by noplay** [comment] 2015-05-10 20:33
0.6 has been released with the fix from @bjoernhaeuser

**Closed by noplay** 2015-05-10 20:33 UTC
Labels: bug
